### ISSUE TITLE
No *.Blend

### ISSUE THREAD

**Issue by Jwoj** [allmyservos/allmyservos#1]
Hi Great work you have done here. I don't seem to be able to locate the *.blend file.

Thanks

**Comment by allmyservos** [comment]
Thanks, the blend file is part of the specification of a robot. The Vanguard spec is packaged up to begin with. The file is in: /specifications/packages/[guid].tar.gz. You can extract it from there. Alternatively in the GUI go to File -> Specification -> Install Specification and install it. That will unpack it and provide a shortcut to the .blend file directly from the app.
